CREATE VIEW V_EMP(EMP_ID,FIRST_NAME,JOB_ID,HIRE_dATE,DEPT_ID) AS 
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, HIRE_DATE, DEPARTMENT_ID    -- 논리적인 집합 
FROM EMPLOYEES 
WHERE JOB_ID = 'ST_CLERK';   ---가상뷰는 메모리를 차지하지 않음 